FROM archlinux

WORKDIR /app

COPY ./dist/*.pacman .

RUN <<EOF
pacman -Syu --noconfirm
pacman -U --noconfirm ./*.pacman
pacman -Syu --noconfirm x11vnc xorg-server-xvfb

EOF

RUN mkdir ~/.vnc && x11vnc -storepasswd 1234 ~/.vnc/passwd

COPY docker/start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 5900

CMD ["/start.sh"]