FROM ubuntu

WORKDIR /app

COPY ./dist/*.deb .

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install ./*.deb -y

RUN apt-get install -qqy x11-apps x11vnc xvfb

RUN mkdir ~/.vnc
RUN x11vnc -storepasswd 1234 ~/.vnc/passwd

COPY docker/start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 5900

CMD ["/start.sh"]